services:
  # PostgreSQL Database
  - type: pserv
    name: supervity-bank-cc-postgres
    plan: starter
    databaseName: supervity_bank_cc
    databaseUser: supervity_bank_cc_user

  # Backend API Service
  - type: web
    name: supervity-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: supervity-bank-cc-postgres
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in Render dashboard
      - key: CORS_ORIGINS
        value: https://supervity-frontend.onrender.com
      - key: APP_ENV
        value: production
      - key: PORT
        value: 8000
      - key: PDF_STORAGE_PATH
        value: ./sample_data
      - key: GENERATED_PDF_STORAGE_PATH
        value: ./generated_documents
    healthCheckPath: /api/health
    buildCommand: echo "Using Docker build"
    startCommand: gunicorn -c gunicorn/prod.py app.main:app

  # Frontend Service
  - type: web
    name: supervity-frontend
    env: docker
    plan: starter
    dockerfilePath: ./supervity-ap-frontend/Dockerfile
    dockerContext: ./supervity-ap-frontend
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://supervity-backend.onrender.com/api
      - key: NODE_ENV
        value: production
    buildCommand: npm run build
    startCommand: node server.js
